---
title: ""
# subtitle: "One-sentence description of your research question"
# author: "SIDs 560622278"
# date: "S1 2026"
format:
  html:
    title-block-banner: true
    code-fold: true
    embed-resources: true
    toc: true
    toc-location: right
    toc-float: true
    include-before-body: data1901-banner.html
    css: style.css
self-contained: true
execute:
  warning: false
  message: false
editor: visual
---

# Executive Summary (Max 50 words)

This is effectively your "Executive Summary" with a concrete insight or action. Type your recommendation here.

# Evidence

## EDA (Max 200 words)

```{r}
library(tidyverse)
library(readxl)
library(here)

#-----Load data--------------------------------------------------------
datapath <- here("data", "1901_2026_s1_data.xlsx")
df <- read_excel(datapath, sheet = "osf_anon_data")

#-----Tidy and compute pre/post change---------------------------------
df_long <- df |>
# filter data
  select(
    gid_pid, group, intervention_bin,
    starts_with("bgase_"), starts_with("agase_")
  ) |>
# change data format from wide to long, so we have:  gid_pid | phase | item | value 
  pivot_longer(
    cols          = starts_with("bgase_") | starts_with("agase_"), # select cols
    names_to      = c("phase", "item"), # separate into two new cols
    names_pattern = "(bgase|agase)_(\\d+)" 
  ) |>
# change to wide, so we have:  gid_pid | item | bgase | agase 
  pivot_wider(names_from = phase, values_from = value) |>
#creating cols
  mutate(
    item = as.integer(item),       # change char "1" to int 1
    diff = agase - bgase,          # calculate difference
    warned = if_else(item <= 2, "Warned", "Non-warned"),          # labeling symptoms
    warned = factor(warned, levels = c("Warned", "Non-warned")),  # order "Warned" before "Non-warned"
    symptom = case_when(           # new col. symptom name 
      item == 1  ~ "Headache",     # if item is "1", assign "Headache"
      item == 2  ~ "Dizziness",
      item == 3  ~ "Nausea",
      item == 4  ~ "Stomach discomfort",
      item == 5  ~ "Breathing problems",
      item == 6  ~ "Palpitation",
      item == 7  ~ "Itching",
      item == 8  ~ "Abnormal sweating",
      item == 9  ~ "Dry mouth",
      item == 10 ~ "Chest pain"
    ),
    # forcats package (from tidyverse) handles factors
    symptom = forcats::fct_reorder(symptom, item), # cast to factor and reorder according to number
    # cast group col to factor and assign order
    group = factor(group, levels = c("NH", "NINSM", "NISM", "INSM", "ISM"))
  )
```

## Research Question 1

::: {.callout-note icon="false"}
## Research Question 1

How do warned symptoms (headache/dizziness) compare to non-warned symptoms?
:::

```{}
```

## Research Question 2 (Linear Model)

Type your research question evidence here. Include testing assumptions of the linear model (residual plot).

## Articles (Max 50 words)

Include any relevant literature to your analysis.

# Acknowledgements

The Acknowledgment section includes a list of group meetings (date and time and attendance), the contribution of each group member, and all resources used (e.g. url of stack overflow, url of Ed post, date and details of drop-in session with tutor).

An AI usage statement including: the name and version of the AI tools, the publisher, the URL, a brief description of the context in which the tool was used. If no AI was used, this must be clearly stated.

A short statement explaining how 1 of the Shared Values and 1 of the Ethical Principles has been adhered to.

## AI usage

AI tool Claude is used for